---
title: "Основы обработки данных с помощью R и Dplyr №2"
format: 
  md:
    output-file: README.md
---

## Цель работы:

-   Развить практические навыки использования языка программирования R для
    обработки данных

-   Закрепить знания базовых типов данных языка R

-   Развить практические навыки использования функций обработки данных пакета
    dplyr – функции select(), filter(), mutate(), arrange(), group_by()

## Исходные данные

1.  OC Windows

2.  Ноутбук

3.  Пакет nycflights13

4.  RStudio

## Общий план выполнения работы

-   Сколько встроенных в пакет nycflights13 датафреймов?

-   Сколько строк в каждом датафрейме?

-   Сколько столбцов в каждом датафрейме?

-   Как просмотреть примерный вид датафрейма?

-   Сколько компаний-перевозчиков (carrier) учитывают эти наборы данных (представлено в наборах дан- ных)?

-   Сколько рейсов принял аэропорт John F Kennedy Intl в мае?

-   Какой самый северный аэропорт?

-   Какой аэропорт самый высокогорный (находится выше всех над уровнем моря)?

-   Какие бортовые номера у самых старых самолетов?

-   Какая средняя температура воздуха была в сентябре в аэропорту John F Kennedy Intl (в градусах Цельсия).

-   Самолеты какой авиакомпании совершили больше всего вылетов в июне?

-   Самолеты какой авиакомпании задерживались чаще других в 2013 году?

-   Оформить отчет в соответствии с шаблоном

## Содержание ЛР

```{r}
data(package="nycflights13")
```

## Оценка результата

Были использованы знания функций `select(), filter(), mutate(), arrange(), group_by()` для решения практических задач.

## Вывод

В результате выполнения работы были:

-   развиты практические навыки использования языка программирования R для обработки данных

-   закреплены знания базовых типов данных языка R

-   развиты практические навыки использования функций обработки данных пакета `dplyr` – функции `select(), filter(), mutate(), arrange(), group_by()`
