---
title: "Использование технологии Yandex DataLens для анализа данных сетевой активности"
format: 
  md:
    output-file: README.md
---

## Цель работы:

1.  Изучить возможности технологии Yandex DataLens для визуального анализа
    структурированных наборов данных

2.  Получить навыки визуализации данных для последующего анализа с помощью
    сервисов Yandex Cloud

3.  Получить навыки создания решений мониторинга/SIEM на базе облачных
    продуктов и открытых программных решений

4.  Закрепить практические навыки использования SQL для анализа данных сетевой
    активности в сегментированной корпоративной сети

## Исходные данные

1.  Персональный компьютер

2.  Браузер

3.  R studio

4.  Yandex DataLens

5.  Yandex Cloud

## Общий план выполнения работы

1.  Настроить подключение к Yandex Query из DataLens

2.  Создать из запроса YandexQuery датасет DataLens

3.  Выполнение заданий

4.  Подготовить отчёт

## Содержание ЛР

## Оценка результата

Проведен анализ сетевой активности в сегментированной корпоративной сети

## Вывод

1.  Были изучены возможности технологии Yandex DataLens для визуального анализа структурированных наборов данных

2.  Получены навыки визуализации данных для последующего анализа с помощью сервиса Yandex Cloud

3.  Получены навыки создания решений мониторинга/SIEM на базе облачных продуктов и открытых программных решений

4.  Закреплены на практике навыки использования SQL для анализа данных сетевой активности в сегментированной корпоративной сети
